language: node_js
node_js:
  - "lts/*"
before_install:
  - npm install -g grunt-cli
  - pwd
  - ls
install:
  - npm install
  - pip install -r requirements.txt
cache:
  directories:
    - "node_modules"
script:
  - npm run build
  - npm test