language: node_js
node_js:
  - "lts/*"
before_install:
  - npm install -g grunt-cli
install:
  - npm install
  - pip install -r requirements.txt
cache:
  directories:
    - "node_modules"
before_script:
  - rm -rf build/static/*
script:
  - npm run build
  - npm test